### ISSUE TITLE
test suite 'TestMx' - ghc: unrecognised flag: --threaded

### ISSUE THREAD

**Issue by juhp** [haskell-distributed/distributed-process-tests#27]
As also mentioned in fpco/stackage#886, with distributed-process-tests-0.4.3.1 TestMx fails to build in Stackage Nightly:

```
Preprocessing test suite 'TestMx' for distributed-process-tests-0.4.3.1...
ghc: unrecognised flag: --threaded
did you mean one of:
  -threaded
```

**Comment by qnikst** [comment]
Thanks for the report!
distributed-process-tests bumped up to 0.4.3.2 with problem fixed.
I've retested all packages in cloud haskell stack with `stack test` - they builds for me, note that some may still have test failures (mostly because tests are not accurately written), this will be eventually fixed. Feel free to open bug report for tests if you expect that there is a real problem.
