### ISSUE TITLE
How best to test all CH libraries

### ISSUE THREAD

**Issue by hyperthunk** [haskell-distributed/distributed-process-tests#29]
I forget why we moved the distributed-process tests out into its own lib in the first place, but I suspect it had to do with using different network-transport implementations. I think this makes it very hard to test other libraries, since we either have to pull all additional library tests into this repo, which is impractical, or replicate a lot of the code here in other projects.

Is there a middle ground? Could this library just provide the plumbing and common code, and the actual test cases move back into the depositor they pertain to (distributed-process), allowing other ch libraries and external authors who are writing ch libraries to take advantage of this library, without having to jump through hoops when setting up travis?

**Comment by mboes** [comment]
It was indeed to test different network-transport implementations. Could you explain which libraries this causes a problem for, and what the problem with Travis CI is? Which libraries need to be running these tests, apart from distributed-process, and any library whose name is of the form `network-transport-*`?

**Comment by hyperthunk** [comment]
Hi @mboes, well this originated a comment made in https://github.com/haskell-distributed/distributed-process/pull/274 about running these tests, but really there are a couple of things I'm asking about (and by all means, I might be barking up the wrong tree..)..

I'd like all the CH libraries to be able to take advantage of being able to run all their tests against multiple network transport implementations, which is a capability this project provides. But I don't want to run all the distributed-process test suits when I do that, just the tests for distributed-process-xyz that I'm working on. I certainly don't want to have to put distributed-process-xyz test suites in this repo (and I'm sure you wouldn't want that either), and when travis detects a change in distributed-process-xyz (or distributed-process itself for that matter), it seems a bit convoluted that it has to grab this project from via a hook and build it whilst pointing to the distributed-process checkout it just fetched, and then invoke `main` in this project to then test distributed-process.

So I'm wondering... Can this project not simply provide the *hooking in different network-transport libraries* capability, e.g., the data type and provide runTCP and runInMemory with the correct args, plus all the Utils.hs stuff,  and the actual test cases reside in distributed-process, and then the distributed-process cabal file declares the test suites with `-DTEST_SUITE_MODULE` and whatnot? That way, distributed-process-xyz test suites can declare this project as a test dependency and make use of those features too (viz runTCP with the correct args and whatnot, all the Utils functions and so on).

Am I way off here? Is there an easier solution to this, such as providing runTCP and runInMemory via Utils.hs or some such? What are your thoughts?

**Comment by mboes** [comment]
I'm afraid I'm still confused... Could you break this down into: "I tried to do <blah> for <foo> reason, but was blocked by <bar>"?

What I'm understanding so far is that you want to run each *ex-platform* library test suite using multiple transports. However, what's the reason? Is this to 

1. further exercise the transports themselves, or
2. to find bugs that would show up in d-p-* with one transport but not the other?

I think if you find a bug in a network transport this way then arguably it's the `network-transport-tests` package that's faulty, because it's not providing enough coverage of the guarantees a transport is supposed to respect. So we shouldn't need to run tests against multiple transports for the purposes of (1). In fact doing so makes us run the risk of codifying invariants at the d-p level or higher that really belong at the n-t layer. For this reason, I seem to remember pushing a **WIP** branch called `import-d-p-tests` back in October that moves d-p-tests back into the d-p repo, and runs the d-p tests using a single (arbitrarily chosen) network transport.

If we follow through with merging that branch (once it's finished), d-p-tests as a separate repo would disappear.

Now, if (2) is important to you and you're tired of the boilerplate for setting up a TCP transport and the like then you could always put that in a util module somewhere if you already have that. If there's that much boilerplate though then arguably we should just make it easier to use n-t-tcp.

I'm not sure how effective (2) as a method of finding race conditions will turn out to be, so I'll be interested to hear back from your experiments there.

Either way, I don't think it's a good idea to put test cases for downstream libraries in distributed-process, or even distributed-process-tests.

**Comment by mboes** [comment]
Hm, apparently Github renders things with angle brackets funny (i.e. not at all). Edited them out of the first paragraph above. Sorry for the confusion.

**Comment by hyperthunk** [comment]
Okay so I think we're in agreement here, insomuchas once `import-d-p-tests` is merged, the test cases will be where they belong. If we could keep this project as a place for those common Utils you mention, and import this library (with all the Utils stuff) as a test dependency for d-p, then all the ex platform libraries can follow suit, and that would be ideal for me!

**Comment by facundominguez** [comment]
Looks like tests where imported back last October:

https://github.com/haskell-distributed/distributed-process/pull/259

**Comment by facundominguez** [comment]
hm, we sho

**Comment by facundominguez** [comment]
Closed accidentally.

**Comment by hyperthunk** [comment]
Okay... So is the travis setup in cloud-Haskell and distributed-process now correct, and shouldn't the submodule for this repo be removed from the umbrella project? And shouldn't we remove all the files from the repo in a commit, update the readme to say it's deprecated, or just the latter?

**Comment by facundominguez** [comment]
Travis is running the tests in distributed-process/distributed-process-tests which is where the package lives now.

> And shouldn't we remove all the files from the repo in a commit, update the readme to say it's deprecated ...

This is fine with me.

**Comment by hyperthunk** [comment]
Awesome, except that all the Utils code in that embedded project is now private to the distributed-process repo and cannot be reused. Is there enough useful code in there to warrant pulling it out, or shall we just replicate that code somewhere else? I was contemplating whether we delete the files in this repo, but instead of deprecating it, let it evolve into a library in which we put common testing capabilities which other CH based projects can leverage. Thoughts...?

**Comment by mboes** [comment]
> Awesome, except that all the Utils code in that embedded project is now private to the distributed-process repo and cannot be reused.

It can be reused, from the moment it's released on Hackage. But...

> Thoughts...?

I'd much rather retire this package entirely and that we start a new one, under a different name, since this no longer contains tests for `distributed-process`. So the naming would be confusing for just a utils package, since `network-transport-tests` *does* contain tests for `network-transport` backends.

I'm still confused as to what kind of code this hypothetical new "testing" package would contain. What "util" code from d-p-tests are you interested in? AFAICS there's only the 12 lines worth of code in `runTCP.hs` and 4 lines of code in `runInMemory.hs`. Do any of the tests in your d-p-* packages require the ability to simulate breaking connections?

**Comment by hyperthunk** [comment]
It's more the kind of code in https://github.com/haskell-distributed/distributed-process-tests/blob/master/src/Control/Distributed/Process/Tests/Internal/Utils.hs that I'm interested in not duplicating, and expanding to generally add more useful testing code that can be utilised elsewhere. It's a small amount of code in there right now, admittedly.

The simulating breaking connections thing is something I'm *very* interested in, but I'm assuming it would be better to use a specialised network-transport for that?

Anyway overall, I agree about retiring this package. I've got another area of testing that I'm interested in implementing, but it will require modifications to distributed-process I think, so I'll raise a ticket there to discuss.

I'm going to close this ticket now, as I think we're all agreed on retiring this package.

**Comment by mboes** [comment]
Ah! Had completely forgotten about that module. Yes, sounds like something worth sticking in a dedicated `test-framework` like package for distributed-process.
